### ISSUE TITLE
2 `@pause Filament Rounout`

### ISSUE THREAD

**Issue by LuckyTurtleDev** [Raabi91/filament_rounout_Repetier#1]
https://github.com/Raabi91/filament_runout_Repetier/blob/437c603aec170715c931f8a7bd7fa6f4bdc4aa79/filament.sh#L17
Why do you send two `@pause Filament Rounout` ?

**Comment by Raabi91** [comment]
the first ist the Pause comand for repetier Server 
the second one ist for M117 message on printer Display

**Comment by LuckyTurtleDev** [comment]
thanks
